13 implement test cases for showcase app
SolidLabResearch/solid-identity-manager pull request #17
Opened 2023-12-12 07:09 UTC by svdwyer

2023-12-12 09:46 UTC, pheyvaer requested changes
The showcase app has both a `package-lock.json` and `yarn.lock`.

2023-12-12 12:59 UTC, svdwyer commented
Having both npm and yarn lock files for the plugin obviously doesn't make sense. The plugin was set up with yarn, so I could simply remove the npm lock file.
But the extension on the other hand uses npm. Shall we all both projects and use npm for both?

2023-12-12 13:01 UTC, svdwyer commented on showcase-app/tests/main.spec.js
> +test('Removing profile inside the extension deactivates the profile', async ({page, mainPage, popupPage}) => {
I meant removing the profile in the extension should deactive that profile in the plugin.
So if the plugin has profile A active (with the "Continue as A" shown), that should not be the case anymore after the profile is removed in the extension

2023-12-12 14:10 UTC, pheyvaer commented on showcase-app/tests/main.spec.js
> +test('Removing profile inside the extension deactivates the profile', async ({page, mainPage, popupPage}) => {
In that case it's better to write exactly that. Now there is also the confusion between "extension" and "plugin".

2024-01-02 13:33 UTC, pheyvaer requested changes
Where are the instructions on how to run the tests?

2024-01-05 16:01 UTC, pheyvaer requested changes
When I start the tests I get this in my terminal:

```shell
)$ npm test

> solid-auth-clientside-showcase@0.0.0 test
> PW_EXPERIMENTAL_SERVICE_WORKER_NETWORK_EVENTS=1 playwright test
[WebServer] Error:   Failed to scan for dependencies from entries:
  /Users/pheyvaer/Development/solid/solid-identity-manager/showcase-app/index.html
/Users/pheyvaer/Development/solid/solid-identity-manager/showcase-app/playwright-report/index.html

  The package "@esbuild/darwin-x64" could not be found, and is needed by esbuild.

If you are installing esbuild with npm, make sure that you don't specify the
"--no-optional" or "--omit=optional" flags. The "optionalDependencies" feature
of "package.json" is used by esbuild to install the correct binary executable
for your current platform.
    at generateBinPath (/Users/pheyvaer/Development/solid/solid-identity-manager/showcase-app/node_modules/esbuild/lib/main.js:1885:15)
    at esbuildCommandAndArgs (/Users/pheyvaer/Development/solid/solid-identity-manager/showcase-app/node_modules/esbuild/lib/main.js:1955:33)
    at ensureServiceIsRunning (/Users/pheyvaer/Development/solid/solid-identity-manager/showcase-app/node_modules/esbuild/lib/main.js:2119:25)
    at Object.context (/Users/pheyvaer/Development/solid/solid-identity-manager/showcase-app/node_modules/esbuild/lib/main.js:2012:33)
    at prepareEsbuildScanner (file:///Users/pheyvaer/Development/solid/solid-identity-manager/showcase-app/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:43097:26)
    at async file:///Users/pheyvaer/Development/solid/solid-identity-manager/showcase-app/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:43597:38
```

2024-01-11 13:25 UTC, svdwyer commented on showcase-app/test-cases.md
> +To run end-to-end tests, you must first have built the plugin (`npm run build`).
it should be run in the project folder: showcase-app
npm will look for a package.json in the folder it is run in.

2024-01-12 08:18 UTC, pheyvaer commented on showcase-app/test-cases.md
> +To run end-to-end tests, you must first have built the plugin (`npm run build`).
But won't that build the showcase app instead of the plugin then?

2024-01-22 11:10 UTC, svdwyer commented on showcase-app/test-cases.md
> +To run end-to-end tests, you must first have built the plugin (`npm run build`).
I'm sorry, i meant it the other way: the build should happen in extension directory (project root)
I will amend the wording

2024-01-23 10:27 UTC, pheyvaer approved these changes

2024-01-23 14:27 UTC, merged