14 input fields should not resemble buttons
SolidLabResearch/solid-identity-manager pull request #19
Opened 2023-12-21 08:23 UTC by svdwyer

2024-01-24 09:22 UTC, pheyvaer requested changes
Make sure that the latest code from `main` is in the branch.

2024-01-25 15:11 UTC, pheyvaer requested changes

2024-01-25 15:11 UTC, pheyvaer commented on src/popup/popup.js
> +  // colors.forEach(
Can't we just delete these lines then?

2024-01-26 12:51 UTC, svdwyer commented on src/popup/popup.js
> +  // colors.forEach(
correct
✔️

2024-01-26 15:02 UTC, pheyvaer approved these changes

2024-01-26 15:14 UTC, merged

2024-01-26 15:14 UTC, svdwyer commented
fixes https://github.com/SolidLabResearch/solid-identity-manager/issues/14