End to end testing using playwright
SolidLabResearch/solid-identity-manager pull request #3
Opened 2023-11-17 12:26 UTC by svdwyer

2023-11-20 09:46 UTC, pheyvaer requested changes

2023-11-20 09:46 UTC, pheyvaer commented on tests/popup-page.js
Documentation is missing from the functions.

2023-11-21 08:50 UTC, svdwyer commented on .prettierrc
correct

2023-11-21 08:52 UTC, svdwyer commented on .gitignore
> +/playwright/.cache/
they shouldn't be. I think I may have run the playwright installation script twice

2023-11-21 08:53 UTC, svdwyer commented on tests/main.spec.js
> +// const WEBID_C = 'https://pod.playground.solidlab.be/c/profile/card#me';
these comments actually should be removed. the WEBIDs are not used

2023-11-21 10:39 UTC, pheyvaer requested changes

2023-11-21 10:39 UTC, pheyvaer commented on tests/main.spec.js
> +  await expect(settingsPage).toHaveTitle(/Manage SOLID profiles/);
Should be "Solid".

2023-11-21 10:39 UTC, pheyvaer commented on tests/main.spec.js
> +  await expect(popup).toHaveTitle(/Add a new SOLID profile/);
Should be "Solid".

2023-11-23 06:41 UTC, pheyvaer approved these changes

2023-11-24 08:47 UTC, merged